Repository redhat-integration/rhi-operator, pull requests merged in 2020-05, with the labels that each got.

#1 Add new self-managed installationType
  deploy/cro-configmaps.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
  pkg/controller/installation/bootstrapReconciler.go
  pkg/controller/installation/types.go
Labels: approved, lgtm, ok-to-test

#19 Update travis ci config
  .travis.yml
Labels: lgtm

#18 Fix and refactor AMQ Streams reconciler pods readiness check
  pkg/products/amqstreams/reconciler.go
  pkg/products/amqstreams/reconciler_test.go
Labels: approved

#17 Fix amqstreams non-operator pods replicas number check
  pkg/products/amqstreams/reconciler.go
Labels: approved, lgtm

#2 Add new installation type environment variable
  deploy/operator.yaml
Labels: approved, do-not-merge/hold, lgtm, ok-to-test

#21 add UTC conversion to test timestamp to align with code comparison
  pkg/controller/subscription/rhmiConfigs/main_test.go
Labels: approved

#23 Fix openshift/api dependency not matching what's generated by operator-sdk v0.15.1
  go.mod
  go.sum
  vendor/github.com/openshift/api/apps/v1/generated.pb.go
  vendor/github.com/openshift/api/apps/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/authorization/v1/generated.pb.go
  vendor/github.com/openshift/api/authorization/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/console/v1/register.go
  vendor/github.com/openshift/api/console/v1/types_console_external_log_links.go
  vendor/github.com/openshift/api/console/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/console/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/image/v1/generated.pb.go
  vendor/github.com/openshift/api/image/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/oauth/v1/generated.pb.go
  vendor/github.com/openshift/api/oauth/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/project/v1/generated.pb.go
  vendor/github.com/openshift/api/project/v1/generated.proto
  vendor/github.com/openshift/api/project/v1/types.go
  vendor/github.com/openshift/api/project/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/project/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.pb.go
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/template/v1/generated.pb.go
  vendor/github.com/openshift/api/template/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/user/v1/generated.pb.go
  vendor/github.com/openshift/api/user/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved
